# Generated by Django 2.0.2 on 2018-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test14', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='details',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='complaint',
            name='isInProgress',
            field=models.BooleanField(default=False),
        ),
    ]
